import { Decimal } from '@prisma/client-runtime-utils'

import type { Input } from '../../__helpers__/integrationTest'

// These scenarios are Oracle-mode specific. In particular, they use Oracle
// identity columns and VARCHAR2 rather than Kingbase MySQL syntax.
export const scenarios: Input['scenarios'] = [
  {
    name: 'findUnique and select by primary key',
    up: `
      CREATE TABLE teams (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(50) NOT NULL UNIQUE,
        active BOOLEAN NOT NULL DEFAULT TRUE
      );
      INSERT INTO teams (name) VALUES ('Ada');
      INSERT INTO teams (name, active) VALUES ('Lin', FALSE);
    `,
    do: (client) => client.teams.findUnique({ where: { id: 2 }, select: { name: true, active: true } }),
    expect: { name: 'Lin', active: false },
  },
  {
    name: 'create, update, and delete use identity RETURNING values',
    up: `
      CREATE TABLE teams (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(50) NOT NULL UNIQUE
      );
    `,
    do: async (client) => {
      const created = await client.teams.create({ data: { name: 'Ada' } })
      const updated = await client.teams.update({ where: { id: created.id }, data: { name: 'Grace' } })
      const deleted = await client.teams.delete({ where: { id: updated.id } })
      return { created, updated, deleted }
    },
    expect: {
      created: { id: 1, name: 'Ada' },
      updated: { id: 1, name: 'Grace' },
      deleted: { id: 1, name: 'Grace' },
    },
  },
  {
    name: 'create with an Oracle SQL default',
    up: `
      CREATE TABLE teams (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(50) NOT NULL DEFAULT 'Ada'
      );
    `,
    do: (client) => client.teams.create({ data: {} }),
    expect: { id: 1, name: 'Ada' },
  },
  {
    name: 'relations and fluent relation queries',
    up: `
      CREATE TABLE users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email VARCHAR2(50) NOT NULL UNIQUE
      );
      CREATE TABLE posts (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        title VARCHAR2(50) NOT NULL,
        CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
      );
      INSERT INTO users (email) VALUES ('ada@prisma.io');
      INSERT INTO posts (user_id, title) VALUES (1, 'A');
      INSERT INTO posts (user_id, title) VALUES (1, 'B');
    `,
    do: (client) => client.users.findUnique({ where: { email: 'ada@prisma.io' } }).posts({ orderBy: { id: 'asc' } }),
    expect: [
      { id: 1, user_id: 1, title: 'A' },
      { id: 2, user_id: 1, title: 'B' },
    ],
  },
  {
    name: 'composite unique constraints and upsert',
    up: `
      CREATE TABLE users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email VARCHAR2(50) NOT NULL,
        name VARCHAR2(50) NOT NULL,
        CONSTRAINT users_email_name_key UNIQUE (email, name)
      );
      INSERT INTO users (email, name) VALUES ('ada@prisma.io', 'Ada');
    `,
    do: (client) =>
      client.users.upsert({
        where: { email_name: { email: 'ada@prisma.io', name: 'Ada' } },
        create: { email: 'ada@prisma.io', name: 'Ada' },
        update: { name: 'Grace' },
      }),
    expect: { id: 1, email: 'ada@prisma.io', name: 'Grace' },
  },
  {
    name: 'filters and updateMany',
    up: `
      CREATE TABLE teams (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(50) NOT NULL,
        active BOOLEAN NOT NULL DEFAULT TRUE
      );
      INSERT INTO teams (name) VALUES ('Prisma One');
      INSERT INTO teams (name) VALUES ('Prisma Two');
      INSERT INTO teams (name) VALUES ('Other');
    `,
    do: async (client) => {
      const updated = await client.teams.updateMany({
        where: { name: { contains: 'Prisma' } },
        data: { active: false },
      })
      const teams = await client.teams.findMany({ where: { active: false }, orderBy: { id: 'asc' } })
      return { updated, teams }
    },
    expect: {
      updated: { count: 2 },
      teams: [
        { id: 1, name: 'Prisma One', active: false },
        { id: 2, name: 'Prisma Two', active: false },
      ],
    },
  },
  {
    name: 'Oracle enum values round trip',
    up: `
      CREATE TYPE post_status AS ENUM ('DRAFT', 'PUBLISHED');
      CREATE TABLE posts (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR2(50) NOT NULL,
        status post_status NOT NULL DEFAULT 'DRAFT'
      );
    `,
    do: async (client) => {
      await client.posts.create({ data: { title: 'Hello' } })
      return client.posts.update({ where: { id: 1 }, data: { status: 'PUBLISHED' } })
    },
    expect: { id: 1, title: 'Hello', status: 'PUBLISHED' },
  },
  {
    name: 'CLOB, BLOB, and NUMBER round trip through the Oracle adapter',
    up: `
      CREATE TABLE oracle_native_types (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        clob_value CLOB NOT NULL,
        blob_value BLOB NOT NULL,
        amount NUMBER(12, 2) NOT NULL
      );
    `,
    do: (client) =>
      client.oracle_native_types.create({
        data: {
          clob_value: 'Kingbase Oracle',
          blob_value: new Uint8Array([1, 2, 3]),
          amount: new Decimal('12.34'),
        },
      }),
    expect: {
      id: 1,
      clob_value: 'Kingbase Oracle',
      blob_value: new Uint8Array([1, 2, 3]),
      amount: new Decimal('12.34'),
    },
  },
  {
    name: 'raw queries preserve Oracle numbered placeholders',
    up: `
      CREATE TABLE raw_queries (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        value VARCHAR2(50) NOT NULL
      );
    `,
    do: (client) => client.$queryRaw`SELECT ${7} AS "value"`,
    expect: [{ value: '7' }],
  },
  {
    name: 'interactive transactions roll back',
    up: `
      CREATE TABLE teams (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(50) NOT NULL UNIQUE
      );
    `,
    do: async (client) => {
      await client
        .$transaction(async (tx) => {
          await tx.teams.create({ data: { name: 'rolled back' } })
          throw new Error('rollback')
        })
        .catch(() => undefined)

      return client.teams.findUnique({ where: { name: 'rolled back' } })
    },
    expect: null,
  },
  {
    name: 'findMany orders Oracle rows in both directions',
    up: `
      CREATE TABLE teams (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(50) NOT NULL,
        rank INTEGER NOT NULL
      );
      INSERT INTO teams (name, rank) VALUES ('Ada', 2);
      INSERT INTO teams (name, rank) VALUES ('Grace', 1);
      INSERT INTO teams (name, rank) VALUES ('Lin', 3);
    `,
    do: async (client) => ({
      ascending: (await client.teams.findMany({ orderBy: { rank: 'asc' } })).map((team) => team.name),
      descending: (await client.teams.findMany({ orderBy: { rank: 'desc' } })).map((team) => team.name),
    }),
    expect: {
      ascending: ['Grace', 'Ada', 'Lin'],
      descending: ['Lin', 'Ada', 'Grace'],
    },
  },
  {
    name: 'pagination uses Oracle OFFSET and FETCH',
    up: `
      CREATE TABLE teams (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(50) NOT NULL
      );
      INSERT INTO teams (name) VALUES ('Ada');
      INSERT INTO teams (name) VALUES ('Grace');
      INSERT INTO teams (name) VALUES ('Lin');
      INSERT INTO teams (name) VALUES ('Toni');
    `,
    do: (client) =>
      client.teams.findMany({
        orderBy: { id: 'asc' },
        skip: 1,
        take: 2,
        select: { name: true },
      }),
    expect: [{ name: 'Grace' }, { name: 'Lin' }],
  },
  {
    name: 'string filters use Oracle VARCHAR2 semantics',
    up: `
      CREATE TABLE teams (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(50) NOT NULL
      );
      INSERT INTO teams (name) VALUES ('Prisma One');
      INSERT INTO teams (name) VALUES ('Prisma Two');
      INSERT INTO teams (name) VALUES ('Other');
    `,
    do: async (client) => ({
      contains: (await client.teams.findMany({ where: { name: { contains: 'Prisma' } }, orderBy: { id: 'asc' } })).map(
        (team) => team.name,
      ),
      startsWith: (await client.teams.findMany({ where: { name: { startsWith: 'Prisma T' } } })).map(
        (team) => team.name,
      ),
      endsWith: (await client.teams.findMany({ where: { name: { endsWith: 'One' } } })).map((team) => team.name),
    }),
    expect: {
      contains: ['Prisma One', 'Prisma Two'],
      startsWith: ['Prisma Two'],
      endsWith: ['Prisma One'],
    },
  },
  {
    name: 'in notIn and empty list filters',
    up: `
      CREATE TABLE teams (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(50) NOT NULL
      );
      INSERT INTO teams (name) VALUES ('Ada');
      INSERT INTO teams (name) VALUES ('Grace');
      INSERT INTO teams (name) VALUES ('Lin');
    `,
    do: async (client) => ({
      in: (await client.teams.findMany({ where: { name: { in: ['Ada', 'Lin'] } }, orderBy: { id: 'asc' } })).map(
        (team) => team.name,
      ),
      notIn: (await client.teams.findMany({ where: { name: { notIn: ['Grace'] } }, orderBy: { id: 'asc' } })).map(
        (team) => team.name,
      ),
      emptyIn: await client.teams.count({ where: { id: { in: [] } } }),
    }),
    expect: {
      in: ['Ada', 'Lin'],
      notIn: ['Ada', 'Lin'],
      emptyIn: 0,
    },
  },
  {
    name: 'null filters and deleteMany',
    up: `
      CREATE TABLE teams (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(50) NOT NULL,
        note VARCHAR2(50)
      );
      INSERT INTO teams (name, note) VALUES ('Ada', NULL);
      INSERT INTO teams (name, note) VALUES ('Grace', 'active');
      INSERT INTO teams (name, note) VALUES ('Lin', NULL);
    `,
    do: async (client) => {
      const nullNames = (await client.teams.findMany({ where: { note: null }, orderBy: { id: 'asc' } })).map(
        (team) => team.name,
      )
      const deleted = await client.teams.deleteMany({ where: { note: null } })
      const remaining = (await client.teams.findMany({ orderBy: { id: 'asc' } })).map((team) => team.name)
      return { nullNames, deleted, remaining }
    },
    expect: {
      nullNames: ['Ada', 'Lin'],
      deleted: { count: 2 },
      remaining: ['Grace'],
    },
  },
  {
    name: 'createMany and aggregate',
    up: `
      CREATE TABLE teams (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(50) NOT NULL,
        score INTEGER NOT NULL
      );
    `,
    do: async (client) => {
      const created = await client.teams.createMany({
        data: [
          { name: 'Ada', score: 10 },
          { name: 'Grace', score: 20 },
          { name: 'Lin', score: 30 },
        ],
      })
      const aggregate = await client.teams.aggregate({ _count: true, _avg: { score: true }, _max: { score: true } })
      return { created, aggregate }
    },
    expect: {
      created: { count: 3 },
      aggregate: { _count: 3, _avg: { score: 20 }, _max: { score: 30 } },
    },
  },
  {
    name: 'composite primary key CRUD',
    up: `
      CREATE TABLE scores (
        team_id INTEGER NOT NULL,
        player_id INTEGER NOT NULL,
        points INTEGER NOT NULL,
        PRIMARY KEY (team_id, player_id)
      );
      INSERT INTO scores (team_id, player_id, points) VALUES (1, 1, 10);
    `,
    do: async (client) => {
      const updated = await client.scores.update({
        where: { team_id_player_id: { team_id: 1, player_id: 1 } },
        data: { points: 20 },
      })
      const found = await client.scores.findUnique({ where: { team_id_player_id: { team_id: 1, player_id: 1 } } })
      return { updated, found }
    },
    expect: {
      updated: { team_id: 1, player_id: 1, points: 20 },
      found: { team_id: 1, player_id: 1, points: 20 },
    },
  },
  {
    name: 'relations include through an Oracle foreign key',
    up: `
      CREATE TABLE users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email VARCHAR2(50) NOT NULL UNIQUE
      );
      CREATE TABLE posts (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        title VARCHAR2(50) NOT NULL,
        CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
      );
      INSERT INTO users (email) VALUES ('ada@prisma.io');
      INSERT INTO posts (user_id, title) VALUES (1, 'A');
      INSERT INTO posts (user_id, title) VALUES (1, 'B');
    `,
    do: (client) =>
      client.users.findUnique({
        where: { email: 'ada@prisma.io' },
        include: { posts: { orderBy: { id: 'asc' } } },
      }),
    expect: {
      id: 1,
      email: 'ada@prisma.io',
      posts: [
        { id: 1, user_id: 1, title: 'A' },
        { id: 2, user_id: 1, title: 'B' },
      ],
    },
  },
  {
    name: 'nested relation create uses Oracle RETURNING values',
    up: `
      CREATE TABLE users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email VARCHAR2(50) NOT NULL UNIQUE
      );
      CREATE TABLE posts (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        title VARCHAR2(50) NOT NULL,
        CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
      );
    `,
    do: (client) =>
      client.users.create({
        data: {
          email: 'ada@prisma.io',
          posts: { create: [{ title: 'A' }, { title: 'B' }] },
        },
        include: { posts: { orderBy: { id: 'asc' } } },
      }),
    expect: {
      id: 1,
      email: 'ada@prisma.io',
      posts: [
        { id: 1, user_id: 1, title: 'A' },
        { id: 2, user_id: 1, title: 'B' },
      ],
    },
  },
  {
    name: 'implicit many-to-many connect uses an Oracle MERGE source row',
    up: `
      CREATE TABLE roles (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(50) NOT NULL UNIQUE
      );
      CREATE TABLE users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email VARCHAR2(50) NOT NULL UNIQUE
      );
      CREATE TABLE "_RoleToUser" (
        "A" INTEGER NOT NULL,
        "B" INTEGER NOT NULL,
        CONSTRAINT "_RoleToUser_A_fkey" FOREIGN KEY ("A") REFERENCES roles(id) ON DELETE CASCADE,
        CONSTRAINT "_RoleToUser_B_fkey" FOREIGN KEY ("B") REFERENCES users(id) ON DELETE CASCADE
      );
      CREATE UNIQUE INDEX "_RoleToUser_AB_unique" ON "_RoleToUser"("A", "B");
      CREATE INDEX "_RoleToUser_B_index" ON "_RoleToUser"("B");
      INSERT INTO roles (name) VALUES ('admin');
    `,
    do: (client) =>
      client.users.create({
        data: {
          email: 'ada@prisma.io',
          roles: { connect: { id: 1 } },
        },
        include: { roles: true },
      }),
    expect: {
      id: 1,
      email: 'ada@prisma.io',
      roles: [{ id: 1, name: 'admin' }],
    },
  },
  {
    name: 'foreign-key SetDefault updates the dependent row',
    up: `
      CREATE TABLE users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email VARCHAR2(50) NOT NULL UNIQUE
      );
      CREATE TABLE posts (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL DEFAULT 1,
        title VARCHAR2(50) NOT NULL,
        CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET DEFAULT
      );
      INSERT INTO users (email) VALUES ('default@prisma.io');
      INSERT INTO users (email) VALUES ('ada@prisma.io');
      INSERT INTO posts (user_id, title) VALUES (2, 'A');
    `,
    do: async (client) => {
      await client.users.delete({ where: { id: 2 } })
      return client.posts.findUnique({ where: { id: 1 } })
    },
    expect: { id: 1, user_id: 1, title: 'A' },
  },
  {
    name: 'batch transactions commit Oracle writes',
    up: `
      CREATE TABLE teams (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(50) NOT NULL UNIQUE
      );
    `,
    do: (client) =>
      client.$transaction([
        client.teams.create({ data: { name: 'Ada' } }),
        client.teams.create({ data: { name: 'Grace' } }),
      ]),
    expect: [
      { id: 1, name: 'Ada' },
      { id: 2, name: 'Grace' },
    ],
  },
  {
    name: 'timestamp and decimal filters bind Oracle values',
    up: `
      CREATE TABLE events (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        occurred_at TIMESTAMP NOT NULL,
        amount NUMBER(12, 2) NOT NULL
      );
      INSERT INTO events (occurred_at, amount) VALUES (TIMESTAMP '2024-01-01 00:00:00', 5.00);
      INSERT INTO events (occurred_at, amount) VALUES (TIMESTAMP '2024-01-02 00:00:00', 10.00);
      INSERT INTO events (occurred_at, amount) VALUES (TIMESTAMP '2024-01-03 00:00:00', 20.00);
    `,
    do: async (client) => ({
      after: await client.events.count({ where: { occurred_at: { gt: new Date('2024-01-01T12:00:00.000Z') } } }),
      amount: await client.events.count({ where: { amount: { gte: new Decimal('10.00') } } }),
    }),
    expect: { after: 2, amount: 2 },
  },
  {
    name: 'executeRaw binds Oracle numbered parameters',
    up: `
      CREATE TABLE teams (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(50) NOT NULL
      );
      INSERT INTO teams (name) VALUES ('Ada');
    `,
    do: async (client) => {
      const updated = await client.$executeRaw`UPDATE teams SET name = ${'Grace'} WHERE id = ${1}`
      const team = await client.teams.findUnique({ where: { id: 1 } })
      return { updated, team }
    },
    expect: { updated: 1, team: { id: 1, name: 'Grace' } },
  },
  {
    name: 'JSON paths and JSON field references use Oracle JSONB semantics',
    up: `
      CREATE TABLE json_documents (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        payload JSON NOT NULL,
        expected_payload JSON NOT NULL
      );
      INSERT INTO json_documents (payload, expected_payload)
        VALUES ('{"kind":"fruit","tags":["apple"]}', '{"kind":"fruit","tags":["apple"]}');
      INSERT INTO json_documents (payload, expected_payload)
        VALUES ('{"kind":"vegetable","tags":["carrot"]}', '{"kind":"fruit","tags":["apple"]}');
    `,
    do: async (client) => {
      const pathMatch = await client.json_documents.findMany({
        where: { payload: { path: ['kind'], equals: 'fruit' } },
        select: { id: true },
      })
      const fieldReferenceMatch = await client.json_documents.findMany({
        where: { payload: { equals: client.json_documents.fields.expected_payload } },
        select: { id: true },
      })

      return { pathMatch, fieldReferenceMatch }
    },
    expect: { pathMatch: [{ id: 1 }], fieldReferenceMatch: [{ id: 1 }] },
  },
  {
    name: 'case-insensitive filters use Oracle semantics',
    up: `
      CREATE TABLE case_filters (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(50) NOT NULL
      );
      INSERT INTO case_filters (name) VALUES ('Prisma');
      INSERT INTO case_filters (name) VALUES ('prisma client');
      INSERT INTO case_filters (name) VALUES ('Other');
    `,
    do: async (client) =>
      (
        await client.case_filters.findMany({
          where: { name: { contains: 'PRISMA', mode: 'insensitive' } },
          orderBy: { id: 'asc' },
          select: { name: true },
        })
      ).map((row) => row.name),
    expect: ['Prisma', 'prisma client'],
  },
  {
    name: 'full-text search compiles Oracle tsquery filters',
    previewFeatures: ['fullTextSearch'],
    up: `
      CREATE TABLE search_documents (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR2(100) NOT NULL
      );
      INSERT INTO search_documents (title) VALUES ('Prisma ORM');
      INSERT INTO search_documents (title) VALUES ('Prisma Client');
      INSERT INTO search_documents (title) VALUES ('Other');
    `,
    do: (client) =>
      client.search_documents.findMany({
        where: { title: { search: 'Prisma & ORM' } },
        select: { id: true, title: true },
      }),
    expect: [{ id: 1, title: 'Prisma ORM' }],
  },
]
