import { type ArgType, type ColumnType, ColumnTypeEnum } from '@prisma-kb/driver-adapter-utils'

/** PostgreSQL wire-protocol OIDs exposed by Kingbase Oracle mode. */
const PostgresTypeId = {
  BOOL: 16,
  BYTEA: 17,
  CHAR: 18,
  NAME: 19,
  INT8: 20,
  INT2: 21,
  INT4: 23,
  TEXT: 25,
  OID: 26,
  JSON: 114,
  XML: 142,
  JSON_ARRAY: 199,
  MONEY: 790,
  MONEY_ARRAY: 791,
  CIDR: 650,
  CIDR_ARRAY: 651,
  FLOAT4: 700,
  FLOAT8: 701,
  BOOL_ARRAY: 1000,
  BYTEA_ARRAY: 1001,
  CHAR_ARRAY: 1002,
  NAME_ARRAY: 1003,
  INT2_ARRAY: 1005,
  INT4_ARRAY: 1007,
  TEXT_ARRAY: 1009,
  INT8_ARRAY: 1016,
  BPCHAR: 1042,
  BPCHAR_ARRAY: 1014,
  VARCHAR: 1043,
  VARCHAR_ARRAY: 1015,
  DATE: 1082,
  DATE_ARRAY: 1182,
  TIME: 1083,
  TIME_ARRAY: 1183,
  FLOAT4_ARRAY: 1021,
  FLOAT8_ARRAY: 1022,
  OID_ARRAY: 1028,
  TIMESTAMP: 1114,
  TIMESTAMP_ARRAY: 1115,
  TIMESTAMPTZ: 1184,
  TIMESTAMPTZ_ARRAY: 1185,
  TIMETZ: 1266,
  NUMERIC: 1700,
  NUMERIC_ARRAY: 1231,
  UUID: 2950,
  UUID_ARRAY: 2951,
  JSONB: 3802,
  JSONB_ARRAY: 3807,
} as const

/**
 * Kingbase Oracle-compatible OIDs generated by rust-kingbase's
 * `oracle_type_gen.rs`. They are PostgreSQL-wire OIDs, not Oracle OCI types.
 */
const KingbaseOracleTypeId = {
  ROWID: 6123,
  ROWID_ARRAY: 6124,
  UROWID: 6125,
  UROWID_ARRAY: 6126,
  DSINTERVAL: 7000,
  DSINTERVAL_ARRAY: 7001,
  YMINTERVAL: 7002,
  YMINTERVAL_ARRAY: 7003,
  BLOB: 8013,
  CLOB: 8014,
  NCLOB: 8015,
  BPCHARBYTE: 8016,
  BPCHARBYTE_ARRAY: 8017,
  VARCHARBYTE: 8018,
  VARCHARBYTE_ARRAY: 8019,
  SYS_DATE: 8020,
  SYS_DATE_ARRAY: 8021,
  BFILE: 8078,
  BFILE_ARRAY: 8079,
  TINYINT: 8100,
  TINYINT_ARRAY: 8101,
} as const

const typeNames: Record<number, string> = Object.fromEntries(
  [...Object.entries(PostgresTypeId), ...Object.entries(KingbaseOracleTypeId)].map(([name, value]) => [
    value,
    name.toLowerCase(),
  ]),
)

export class UnsupportedOracleNativeDataType extends Error {
  readonly type: string

  constructor(typeId: number) {
    super(`Unsupported column type ${typeNames[typeId] ?? typeId}`)
    this.name = 'UnsupportedNativeDataType'
    this.type = typeNames[typeId] ?? String(typeId)
  }
}

export function fieldToOracleColumnType(fieldTypeId: number): ColumnType {
  switch (fieldTypeId) {
    case PostgresTypeId.INT2:
    case PostgresTypeId.INT4:
    case KingbaseOracleTypeId.TINYINT:
      return ColumnTypeEnum.Int32
    case PostgresTypeId.INT8:
    case PostgresTypeId.OID:
      return ColumnTypeEnum.Int64
    case PostgresTypeId.FLOAT4:
      return ColumnTypeEnum.Float
    case PostgresTypeId.FLOAT8:
      return ColumnTypeEnum.Double
    case PostgresTypeId.BOOL:
      return ColumnTypeEnum.Boolean
    case PostgresTypeId.NUMERIC:
    case PostgresTypeId.MONEY:
      return ColumnTypeEnum.Numeric
    case PostgresTypeId.DATE:
      return ColumnTypeEnum.Date
    case PostgresTypeId.TIME:
    case PostgresTypeId.TIMETZ:
      return ColumnTypeEnum.Time
    case PostgresTypeId.TIMESTAMP:
    case PostgresTypeId.TIMESTAMPTZ:
    case KingbaseOracleTypeId.SYS_DATE:
      return ColumnTypeEnum.DateTime
    case PostgresTypeId.JSON:
    case PostgresTypeId.JSONB:
      return ColumnTypeEnum.Json
    case PostgresTypeId.UUID:
      return ColumnTypeEnum.Uuid
    case PostgresTypeId.BYTEA:
    case KingbaseOracleTypeId.BLOB:
      return ColumnTypeEnum.Bytes
    case PostgresTypeId.CHAR:
      return ColumnTypeEnum.Character
    case PostgresTypeId.BPCHAR:
    case PostgresTypeId.TEXT:
    case PostgresTypeId.VARCHAR:
    case PostgresTypeId.NAME:
    case PostgresTypeId.XML:
    case KingbaseOracleTypeId.ROWID:
    case KingbaseOracleTypeId.UROWID:
    case KingbaseOracleTypeId.CLOB:
    case KingbaseOracleTypeId.NCLOB:
    case KingbaseOracleTypeId.BPCHARBYTE:
    case KingbaseOracleTypeId.VARCHARBYTE:
    case KingbaseOracleTypeId.BFILE:
      return ColumnTypeEnum.Text

    // Prisma scalar lists are deliberately not exposed for Kingbase Oracle.
    // PostgreSQL-compatible catalogs can nevertheless return these arrays.
    // Do not add Oracle extension arrays here: kingbasedb returns their
    // PostgreSQL array literal as one string, not as decoded elements.
    case PostgresTypeId.TEXT_ARRAY:
    case PostgresTypeId.NAME_ARRAY:
    case PostgresTypeId.VARCHAR_ARRAY:
      return ColumnTypeEnum.TextArray
    default:
      // User-defined and enum types are returned as text. The query schema
      // determines whether the value is ultimately represented as an enum.
      if (fieldTypeId >= 16384) {
        return ColumnTypeEnum.Text
      }
      throw new UnsupportedOracleNativeDataType(fieldTypeId)
  }
}

export function mapOracleArg<A>(arg: A | Date, argType: ArgType): null | unknown[] | string | Uint8Array | A {
  if (arg === null) {
    return null
  }

  if (Array.isArray(arg) && argType.arity === 'list') {
    return arg.map((value) => mapOracleArg(value, argType))
  }

  if (typeof arg === 'string' && argType.scalarType === 'datetime') {
    arg = new Date(arg)
  }

  if (arg instanceof Date) {
    switch (argType.dbType) {
      case 'TIME':
      case 'TIMETZ':
        return formatTime(arg)
      case 'TIMESTAMPTZ':
      case 'TIMESTAMPLOCALTZ':
        return arg.toISOString()
      default:
        // Oracle DATE stores both calendar and wall-clock components. It is
        // therefore intentionally handled like TIMESTAMP rather than the
        // PostgreSQL DATE OID used for Prisma's date-only values.
        return formatDateTime(arg)
    }
  }

  if (typeof arg === 'string' && argType.scalarType === 'bytes') {
    return Buffer.from(arg, 'base64')
  }

  if (ArrayBuffer.isView(arg)) {
    return new Uint8Array(arg.buffer, arg.byteOffset, arg.byteLength)
  }

  return arg
}

type ResultField = {
  dataTypeID: number
}

const jsonTypeIds = new Set<number>([PostgresTypeId.JSON, PostgresTypeId.JSONB])
const dateTypeIds = new Set<number>([PostgresTypeId.DATE])
const timeTypeIds = new Set<number>([PostgresTypeId.TIME, PostgresTypeId.TIMETZ])
const dateTimeTypeIds = new Set<number>([
  PostgresTypeId.TIMESTAMP,
  PostgresTypeId.TIMESTAMPTZ,
  KingbaseOracleTypeId.SYS_DATE,
])
const binaryTypeIds = new Set<number>([PostgresTypeId.BYTEA, KingbaseOracleTypeId.BLOB])
const int32TextTypeIds = new Set<number>([KingbaseOracleTypeId.TINYINT])

export function mapOracleRow(row: unknown[] | Record<string, unknown>, fields?: ResultField[]): unknown[] {
  const values = Array.isArray(row) ? row : Object.values(row)

  return values.map((value, index) => mapOracleResultValue(value, fields?.[index]?.dataTypeID))
}

function mapOracleResultValue(value: unknown, typeId?: number): unknown {
  if (value === null || value === undefined) {
    return value
  }

  if (Array.isArray(value)) {
    if (typeId !== undefined && jsonTypeIds.has(typeId)) {
      return JSON.stringify(value)
    }
    return value.map((element) => mapOracleResultValue(element, typeId))
  }

  if (typeof value === 'bigint') {
    return value.toString()
  }

  // kingbasedb requests Oracle extension types in text format. TINYINT is a
  // signed one-byte integer on the server, so expose it as the numeric value
  // promised by ColumnTypeEnum.Int32 instead of leaking the wire string.
  if (typeId !== undefined && int32TextTypeIds.has(typeId)) {
    return Number(value)
  }

  if (typeId !== undefined && jsonTypeIds.has(typeId)) {
    return normalizeJsonResult(value)
  }

  if (typeId !== undefined && dateTypeIds.has(typeId)) {
    return value instanceof Date ? formatDate(value) : String(value).slice(0, 10)
  }

  if (typeId !== undefined && timeTypeIds.has(typeId)) {
    return value instanceof Date ? formatTime(value) : String(value)
  }

  if (typeId !== undefined && dateTimeTypeIds.has(typeId)) {
    // kingbasedb parses both Oracle DATE and PostgreSQL-wire TIMESTAMP
    // values as a local JS Date. These database types have no offset, so
    // retain their local wall-clock components and expose them as UTC.
    return normalizeDateTimeResult(
      value,
      typeId === PostgresTypeId.TIMESTAMP || typeId === KingbaseOracleTypeId.SYS_DATE,
    )
  }

  if (typeId !== undefined && binaryTypeIds.has(typeId)) {
    return normalizeBytesResult(value)
  }

  return value
}

function formatDateTime(date: Date): string {
  const pad = (n: number, z = 2) => String(n).padStart(z, '0')
  const ms = date.getUTCMilliseconds()
  return (
    pad(date.getUTCFullYear(), 4) +
    '-' +
    pad(date.getUTCMonth() + 1) +
    '-' +
    pad(date.getUTCDate()) +
    ' ' +
    pad(date.getUTCHours()) +
    ':' +
    pad(date.getUTCMinutes()) +
    ':' +
    pad(date.getUTCSeconds()) +
    (ms ? '.' + String(ms).padStart(3, '0') : '')
  )
}

function formatDate(date: Date): string {
  const pad = (n: number, z = 2) => String(n).padStart(z, '0')
  return pad(date.getUTCFullYear(), 4) + '-' + pad(date.getUTCMonth() + 1) + '-' + pad(date.getUTCDate())
}

function formatTime(date: Date): string {
  const pad = (n: number, z = 2) => String(n).padStart(z, '0')
  const ms = date.getUTCMilliseconds()
  return (
    pad(date.getUTCHours()) +
    ':' +
    pad(date.getUTCMinutes()) +
    ':' +
    pad(date.getUTCSeconds()) +
    (ms ? '.' + String(ms).padStart(3, '0') : '')
  )
}

function normalizeJsonResult(value: unknown): string {
  if (typeof value !== 'string') {
    return JSON.stringify(value)
  }

  try {
    JSON.parse(value)
    return value
  } catch {
    // A JSON scalar string is returned without its JSON quotes by the driver.
    // The query protocol expects a serialized JSON value, so add them back.
    return JSON.stringify(value)
  }
}

function normalizeDateTimeResult(value: unknown, preserveLocalWallTime = false): string {
  if (value instanceof Date) {
    if (preserveLocalWallTime) {
      return formatOracleDateTime(value)
    }
    return value.toISOString()
  }

  const text = String(value).replace(' ', 'T')
  if (/[zZ]|[+-]\d{2}(?::?\d{2})?$/.test(text)) {
    return text
  }

  return `${text}+00:00`
}

function formatOracleDateTime(date: Date): string {
  // kingbasedb inherits pg-types' timestamp parser, which constructs a Date
  // from the database's offset-less wall-clock components in the Node process
  // time zone. Local getters recover those original components; UTC getters
  // would shift Oracle DATE/TIMESTAMP values outside UTC environments.
  const pad = (n: number, z = 2) => String(n).padStart(z, '0')
  const ms = date.getMilliseconds()
  return (
    pad(date.getFullYear(), 4) +
    '-' +
    pad(date.getMonth() + 1) +
    '-' +
    pad(date.getDate()) +
    'T' +
    pad(date.getHours()) +
    ':' +
    pad(date.getMinutes()) +
    ':' +
    pad(date.getSeconds()) +
    (ms ? '.' + String(ms).padStart(3, '0') : '') +
    '+00:00'
  )
}

function normalizeBytesResult(value: unknown): unknown {
  if (ArrayBuffer.isView(value)) {
    return Buffer.from(value.buffer, value.byteOffset, value.byteLength)
  }

  if (typeof value !== 'string') {
    return value
  }

  if (value.startsWith('0x') || value.startsWith('0X') || value.startsWith('\\x')) {
    return Buffer.from(value.slice(2), 'hex')
  }

  return value
}
