import * as fs from 'node:fs/promises'

import { expect, test } from 'bun:test'

test('prisma.config.ts should match snapshot', async () => {
  const config = await fs.readFile('./prisma.config.ts', 'utf8')
  expect(config).toMatchInlineSnapshot(`
    "// This file was generated by Prisma, and assumes you run Prisma commands using \`bun --bun run prisma-kb [command]\`.
    import { defineConfig, env } from "prisma-kb/config";

    export default defineConfig({
      schema: "prisma/schema.prisma",
      migrations: {
        path: "prisma/migrations",
      },
      datasource: {
        url: env("DATABASE_URL"),
      },
    });
    "
  `)
})
